# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 573ed6bd91023e2abdfcf2f06a0488e9d58b562005e691ced82b44ad1be05fb503e02aedf34e4191578b424196e8a6e07c1428f89e0144d4e174a5944104a9c6

test:
  secret_key_base: c89c15a3bc91db22b6c4b0411ea4db513f1f1fd6017d96d76899ac050146afcc3b287766bd5e745f94cb588d6fac3c8cd05687694ae00ca76d031598daaad8b9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
